<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>netstandard2.1;net8.0;net9.0</TargetFrameworks>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <LangVersion>13</LangVersion>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <EnableNETAnalyzers>True</EnableNETAnalyzers>
      <AnalysisLevel>latest</AnalysisLevel>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <PackageId>BitcoderCZ.Fancade.Runtime.Simulated</PackageId>
      <PackageTags>library;fancade</PackageTags>
      <Version>1.0.0-develop.35</Version>
      <Description>Base package for BitcoderCZ.Fancade.Runtime.Simulated.*</Description>
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
      <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BitcoderCZ.Maths" Version="1.2.0" />
    <PackageReference Include="hamarb123.Analyzers" Version="1.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.2" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitcoderCZ.Fancade.Editing\BitcoderCZ.Fancade.Editing.csproj" />
    <ProjectReference Include="..\BitcoderCZ.Fancade.Runtime\BitcoderCZ.Fancade.Runtime.csproj" />
    <ProjectReference Include="..\BitcoderCZ.Fancade\BitcoderCZ.Fancade.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) == 'netstandard2.1'">
		<Reference Include="Bcl.CollectionsMarshal">
			<HintPath>..\..\libs\Bcl.CollectionsMarshal.dll</HintPath>
		</Reference>
  </ItemGroup>

</Project>
